### ISSUE TITLE
Crash on latest version

### ISSUE THREAD

**Issue by vinnyhorgan** [raylib-extras/rlImGui-cs#17]
Hi, I'm using the latest versions of everything from nuget, these are the dependencies:

``` xml
  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.90.0.1" />
    <PackageReference Include="Raylib-cs" Version="5.0.0" />
    <PackageReference Include="rlImgui-cs" Version="2.0.0" />
  </ItemGroup>
```

When running the simple demo program from the repo, i get this error:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ImGuiNET.RangeAccessor`1.get_Item(Int32 index)
   at rlImGui_cs.rlImGui.FrameEvents()
   at rlImGui_cs.rlImGui.Begin(Single dt)
   at Program.Main() in Program.cs:line 29
```

I changed the version of ImGuiNET to 1.89.9.3 which nuget states as minimum required version and everything works.

Thanks a lot!

**Comment by JeffM2501** [comment]
The package has been updated to 2.0.1 to work with ImGui 1.90
